"""
Django settings for kicwebpro project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^)@j4@4%s80p@&xif*&kmti#81)n5wbarcnl7!du8^42kemzwh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "member" , # 7 # migrate app
    "board",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kicwebpro.urls" # project name
                                # 

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/'templates'], # 6 html 폴더
        #"DIRS": [], 
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kicwebpro.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# =============================================================================
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
# =============================================================================

DATABASES = { # settings.py > mariaDB설정
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": 'kicdb', # database명
        'USER' : 'kic',
        'PASSWORD' : '1111',
        'HOST' : 'localhost',
        'PORT' : '3307',
                
    }
}


# MariaDB 할땐 여기▲에 추가를 해야함

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# 기본 설정 LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "ko-kr" # 세팅 변경부분 1

# TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Seoul" # 2

USE_I18N = True

# USE_TZ = True # 타임존을 USE로 할래?
USE_TZ = False # 3


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = "static/" # css,js,image 위치
STATIC_URL = "/static/" # 4

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

import os # 5
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')] #css,js,image 파일폴더 위치
# C:\Users\KITCOOP\kicpython\django\kicwebpro 폴더 안에
# static, templates 폴더 두개생성

# 8 파일 업로드 폴더, url 설정
MEDIA_URL="/file/"
MEDIA_ROOT = os.path.join(BASE_DIR,"file")


























